//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voto.Consolidate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxDestinationRootSetting {
            get {
                return ((string)(this["textBoxDestinationRootSetting"]));
            }
            set {
                this["textBoxDestinationRootSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonCopySetting {
            get {
                return ((bool)(this["radioButtonCopySetting"]));
            }
            set {
                this["radioButtonCopySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonMoveSetting {
            get {
                return ((bool)(this["radioButtonMoveSetting"]));
            }
            set {
                this["radioButtonMoveSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxOverwriteSetting {
            get {
                return ((bool)(this["checkBoxOverwriteSetting"]));
            }
            set {
                this["checkBoxOverwriteSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonConsolidationSelectionAllSetting {
            get {
                return ((bool)(this["radioButtonConsolidationSelectionAllSetting"]));
            }
            set {
                this["radioButtonConsolidationSelectionAllSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonConsolidationSelectionOldSetting {
            get {
                return ((bool)(this["radioButtonConsolidationSelectionOldSetting"]));
            }
            set {
                this["radioButtonConsolidationSelectionOldSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Slider_ValueSetting {
            get {
                return ((int)(this["Slider_ValueSetting"]));
            }
            set {
                this["Slider_ValueSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonSubfolderConsolidationDateSetting {
            get {
                return ((bool)(this["radioButtonSubfolderConsolidationDateSetting"]));
            }
            set {
                this["radioButtonSubfolderConsolidationDateSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonSubfolderLastWriteDateSetting {
            get {
                return ((bool)(this["radioButtonSubfolderLastWriteDateSetting"]));
            }
            set {
                this["radioButtonSubfolderLastWriteDateSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SourceDirectorySetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SourceDirectorySetting"]));
            }
            set {
                this["SourceDirectorySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicTiffSetting {
            get {
                return ((bool)(this["PicTiffSetting"]));
            }
            set {
                this["PicTiffSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicPngSetting {
            get {
                return ((bool)(this["PicPngSetting"]));
            }
            set {
                this["PicPngSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicGifSetting {
            get {
                return ((bool)(this["PicGifSetting"]));
            }
            set {
                this["PicGifSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicJpegSetting {
            get {
                return ((bool)(this["PicJpegSetting"]));
            }
            set {
                this["PicJpegSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicJpgSetting {
            get {
                return ((bool)(this["PicJpgSetting"]));
            }
            set {
                this["PicJpgSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicPsdSetting {
            get {
                return ((bool)(this["PicPsdSetting"]));
            }
            set {
                this["PicPsdSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicBmpSetting {
            get {
                return ((bool)(this["PicBmpSetting"]));
            }
            set {
                this["PicBmpSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PicRawSetting {
            get {
                return ((bool)(this["PicRawSetting"]));
            }
            set {
                this["PicRawSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VidAviSetting {
            get {
                return ((bool)(this["VidAviSetting"]));
            }
            set {
                this["VidAviSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VidFlvSetting {
            get {
                return ((bool)(this["VidFlvSetting"]));
            }
            set {
                this["VidFlvSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VidWmvSetting {
            get {
                return ((bool)(this["VidWmvSetting"]));
            }
            set {
                this["VidWmvSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VidMovSetting {
            get {
                return ((bool)(this["VidMovSetting"]));
            }
            set {
                this["VidMovSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VidMp4Setting {
            get {
                return ((bool)(this["VidMp4Setting"]));
            }
            set {
                this["VidMp4Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VidMpgSetting {
            get {
                return ((bool)(this["VidMpgSetting"]));
            }
            set {
                this["VidMpgSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VidMtsSetting {
            get {
                return ((bool)(this["VidMtsSetting"]));
            }
            set {
                this["VidMtsSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection GoogleAlbumsSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GoogleAlbumsSetting"]));
            }
            set {
                this["GoogleAlbumsSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxDeleteEmptyDirectories {
            get {
                return ((bool)(this["checkBoxDeleteEmptyDirectories"]));
            }
            set {
                this["checkBoxDeleteEmptyDirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxDeleteDuplicateFiles {
            get {
                return ((bool)(this["checkBoxDeleteDuplicateFiles"]));
            }
            set {
                this["checkBoxDeleteDuplicateFiles"] = value;
            }
        }
    }
}
